version: "3.8"

services:
  gourney-api:
    build:
      context: ../
      dockerfile: development/Dockerfile
    container_name: gourney
    image: gourney
    restart: "no"
    ports:
      - 8090:8090
    volumes:
      - ../:/app
    networks:
      - gourney

  gourney-db:
    image: postgres:14-alpine
    container_name: gourney-db
    restart: "no"
    environment:
      POSTGRES_DB: gourney
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 8091:5432
    networks:
      - gourney

networks:
  gourney: null
