service:
  api:
    port: "8090"

database:
  mongodb:
    uri: mongodb://localhost:27017
    databases:
      blog: "blog"
      log: "log"
    collections:
      posts: "posts"
      post_logs: "post_logs"

broker:
  rabbitmq:
    uri: amqp://root:root@localhost:5672/
    exchanges:
      logs_topic: "logs_topic"
        
