// Code generated by mockery (devel). DO NOT EDIT.

package repository_mock

import (
	repo "github.com/arsura/gourney/pkg/repositories"
	mock "github.com/stretchr/testify/mock"
)

// CurrencyRepo is an autogenerated mock type for the CurrencyRepo type
type MockCurrencyRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *MockCurrencyRepo) Create(p *repo.Currency) (int64, error) {
	ret := _m.Called(p)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*repo.Currency) int64); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*repo.Currency) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOneById provides a mock function with given fields: id
func (_m *MockCurrencyRepo) FindOneById(id int64) (*repo.Currency, error) {
	ret := _m.Called(id)

	var r0 *repo.Currency
	if rf, ok := ret.Get(0).(func(int64) *repo.Currency); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Currency)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
