on:
  workflow_dispatch:

jobs:
  display-variables:
    name: "Hi"
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Use variables
      run: |
        echo "repository variable : ${{ vars.TEST }}"
